name: Main

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ACTIONS_RUNNER_DEBUG: true # Enable debug logs

jobs:
  cache-node-modules:
    name: Cache node_modules
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-dependencies
        with:
          lookup-only: true

  code-quality:
    name: Code Quality
    runs-on: ubuntu-22.04
    needs: [cache-node-modules]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/install-dependencies

      - name: Lint Android files
        run: yarn lint:android

      - name: Types check
        run: yarn ts

      - name: Lib build
        run: yarn build

      - name: Lint files
        run: yarn lint
        # required to run after `yarn build`

  build-android:
    name: Build Android
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        new_arch_enabled: [ 1, 0 ]
        rn_ver: [latest ] # also, can be any npm tag: 0.71-stable, next, nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build-app
        with:
          arch: arm64-v8a
          new-arch-enabled: ${{ matrix.new_arch_enabled }}
          rn-ver: ${{ matrix.rn_ver }}
          module-to-install: file:${{ github.workspace }}
          store-artifacts: true
          platform: android

  build-ios:
    name: Build iOS
    runs-on: macos-14
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        new_arch_enabled: [ 1, 0 ]
        rn_ver: [latest ] # also, can be any npm tag: 0.71-stable, next, nightly
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/build-app
        with:
          new-arch-enabled: ${{ matrix.new_arch_enabled }}
          rn-ver: ${{ matrix.rn_ver }}
          module-to-install: file:${{ github.workspace }}
          store-artifacts: true
          platform: ios
